######################################################################
##
## Filename: Communication_demux.udo
## Created on: Mon Oct 24 12:09:19 Sri Lanka Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
