######################################################################
##
## Filename: Communication_register.udo
## Created on: Fri Oct 21 01:09:55 Sri Lanka Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
