######################################################################
##
## Filename: Control_Unit.udo
## Created on: Sat Oct 22 09:39:24 Sri Lanka Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
