######################################################################
##
## Filename: Instruction_register.udo
## Created on: Fri Oct 21 12:02:44 Sri Lanka Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
